### ISSUE TITLE
 The maximum context length is over,but I just ask Jarvis a few question.Obviously the length is short, but it is wrong.Look at these pictures below.

### ISSUE THREAD

**Issue by kawuwa** [alondmnt/joplin-plugin-jarvis#3]
![图片](https://user-images.githubusercontent.com/92298154/226085085-a28e5d98-cfd8-4b33-a842-a423fe8fd64b.png)
![图片](https://user-images.githubusercontent.com/92298154/226085182-4a21e7d8-4be8-40d6-9bd7-2a4db3e63262.png)

How to speak English?
erro:~~~
after I click ok
![图片](https://user-images.githubusercontent.com/92298154/226085358-387e06cd-eac8-406c-a77f-a3f901a7ef85.png)

**Comment by alondmnt** [comment]
I'll try to explain the error, and suggest a workaround.

1. When sending a request to GPT, the app has to estimate in advance the token length of the input, and add it to the desired length of the output (so that input length + output length = max tokens).

2. This can either be done using model-specific tools (tokenizers), or roughly estimated using heuristics. I use the latter at the moment, because I ran into trouble using a tokenizer. Therefore, Jarvis' estimation is not perfect, and sometimes underestimates the true length of the input. This is especially true for shorter prompts, where the estimation error tends to be larger. In your example, Jarvis estimated the input length at 2 tokens, but in practice, on the OpenAI server, it turned out to be 23.

3. The best solution I can offer for now is to **set the `max_tokens` to something close to 4097 but a little lower, like 4000**. When I do that, I rarely get these error messages.

4. In any case, the error is automatically resolved by Jarvis, by decreasing the token estimation and re-sending the request.

5. I think I will change the maximal value to be lower than 4096, to try to avoid these problems in the future.

**Comment by alondmnt** [comment]
BTW, this is why the default value of `max_tokens` was set to 4000 since v0.3.0

**Comment by kawuwa** [comment]
Successfully! Thank you very much!😃
