### ISSUE TITLE
Azure OpenAI API support

### ISSUE THREAD

**Issue by maskshell** [alondmnt/joplin-plugin-jarvis#9]
Can you provide support for Azure OpenAI API? Thanks!

**Comment by alondmnt** [comment]
I don't have access to Azure OpenAI (it requires an application form). But you can try the attached version and see if it works. In order to test it, change the settings:

1. Enter your `Azure OpenAI API key`.
2. Select the `Chat Model` "(online) Azure OpenAI (experimental)".
3. In the advanced settings, set your `Azure OpenAI text generation model ID` and your `Azure OpenAI API endpoint`.

I'm curious to know if this blind attempt worked.

Please note that as I don't have access to Azure, I cannot guarantee to support this API if MS introduces any breaking changes.

[joplin.plugin.alondmnt.jarvis.jpl.zip](https://github.com/alondmnt/joplin-plugin-jarvis/files/11986242/joplin.plugin.alondmnt.jarvis.jpl.zip)
(Unzip the file and install the plugin manually from `Settings-->Plugins-->Manage your plugins-->Install from file`)

**Comment by alondmnt** [comment]
Also try version ≥0.7.0 which _should_ support Azure OpenAI (hasn't been tested yet).
